### ISSUE TITLE
HistoryFormSheet 에서 날짜필드 순서 바꿀때 문제 

### ISSUE THREAD

**Issue by jungkoo** [jungkoo/taxdoc#13]
코드 만들때 A:A 필드가 날짜 스탬프가 올거라고 생각했는데... (기본적으로는 맞다)
하지만  다음과 같이 필드 순서 변경도 가능한가 보다. 

![image](https://user-images.githubusercontent.com/2881314/80938007-60a1e680-8e12-11ea-8935-9c253841f410.png)

그래서 해당 케이스가 아닌경우 적용 가능한 방법을 기능에 추가해야한다.

**Comment by jungkoo** [comment]
https://github.com/jungkoo/taxdoc/pull/14

다음과 같이 historyForm 에  timestamp_column_name 옵션이 추가됨.

```
sheet = HistoryFormSheet(GoogleFormSheet(url=_url, timestamp_column_name="B"),
                                 db_path="history.json")
```


그리고 next_seq 가 skip 된 offset 은 인지 못하는 문제가 있었음. 
실제 날짜 검증후 skip 된 카운트를 써야 하나 1만 올라가는 버그가 존재했음.
그래서 러시안페인트공 문제와 유사하게 offset skip 저장이 안되서, 앞데이터부터 다시 스캔하여

https://github.com/jungkoo/taxdoc/pulls?q=is%3Apr+is%3Aclosed

api 요청횟수를 넘어가버린적이 많음.


```
Traceback (most recent call last):
  File "/home/tost/taxdoc/google_form_bot.py", line 132, in <module>
    run(exit_member_msg, "탈퇴가입자봇", is_send_message)
  File "/home/tost/taxdoc/google_form_bot.py", line 118, in run
    _msg = fun()
  File "/home/tost/taxdoc/google_form_bot.py", line 89, in exit_member_msg
    for r in _history_result_more_safe(_url, "./history_exit_member.json"):
  File "/home/tost/taxdoc/google_form_bot.py", line 19, in _history_result_more_safe
    raise e
  File "/home/tost/taxdoc/google_form_bot.py", line 14, in _history_result_more_safe
    for r in sheet.more():
  File "/home/tost/taxdoc/taxdoc/sheet.py", line 87, in more
    for row in self._sheet.find_date(start_date=self._date, start_seq=self._next_seq):
  File "/home/tost/taxdoc/taxdoc/sheet.py", line 52, in find_date
    **{"start_seq": start_seq, "timestamp_column_name": self._timestamp_column_name})):
  File "/usr/local/lib/python3.6/site-packages/gspread/utils.py", line 571, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/gspread/models.py", line 999, in get
    response = self.spreadsheet.values_get(range_name, params=params)
  File "/usr/local/lib/python3.6/site-packages/gspread/models.py", line 192, in values_get
    r = self.client.request('get', url, params=params)
  File "/usr/local/lib/python3.6/site-packages/gspread/client.py", line 73, in request
    raise APIError(response)
gspread.exceptions.APIError: {'code': 429, 'message': "Quota exceeded for quota group 'ReadGroup' and limit 'Read requests per user per 100 seconds' of service 'sheets.googleapis.com' for consumer 'project_number:1098287552704'.", 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Google developer console API key', 'url': 'https://console.developers.google.com/project/1098287552704/apiui/credential'}]}]}
```

**Comment by jungkoo** [comment]
https://github.com/jungkoo/taxdoc/pull/15

수정완료
